# Generated by Django 2.0.9 on 2018-12-12 20:18

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import guides.models
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ascendancy', models.CharField(choices=[('Scion', (('Ascendant', 'Ascendant'),)), ('Shadow', (('Trickster', 'Trickster'), ('Saboteur', 'Saboteur'), ('Assassin', 'Assassin'))), ('Duelist', (('Slayer', 'Slayer'), ('Gladiator', 'Gladiator'), ('Champion', 'Champion'))), ('Witch', (('Necromancer', 'Necromancer'), ('Elementalist', 'Elementalist'), ('Occultist', 'Occultist'))), ('Templar', (('Inquisitor', 'Inquisitor'), ('Hierophant', 'Hierophant'), ('Guardian', 'Guardian'))), ('Marauder', (('Juggernaut', 'Juggernaut'), ('Berserker', 'Berserker'), ('Chieftain', 'Chieftain'))), ('Ranger', (('Deadeye', 'Deadeye'), ('Raider', 'Raider'), ('Pathfinder', 'Pathfinder')))], max_length=20, null=True)),
                ('character_class', models.CharField(choices=[(guides.models.CharacterChoices('Shadow'), 'Shadow'), (guides.models.CharacterChoices('Ranger'), 'Ranger'), (guides.models.CharacterChoices('Marauder'), 'Marauder'), (guides.models.CharacterChoices('Duelist'), 'Duelist'), (guides.models.CharacterChoices('Templar'), 'Templar'), (guides.models.CharacterChoices('Witch'), 'Witch'), (guides.models.CharacterChoices('Scion'), 'Scion')], max_length=15, null=True)),
                ('content', django.contrib.postgres.fields.jsonb.JSONField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('items', django.contrib.postgres.fields.jsonb.JSONField()),
                ('patch_version', models.CharField(max_length=10)),
                ('primary_skill', models.CharField(max_length=100)),
                ('published', models.BooleanField(default=False)),
                ('score', models.IntegerField()),
                ('title', models.CharField(max_length=155)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
    ]
